config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    get 'zip_code', to: 'zip_code#show'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end
  
  devise_for :admins, skip: [:registrations]
  devise_for :users

  get 'inicio', to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'
  
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/site/answer_controller.rb
class Site::AnswerController < SiteController
    def question
        # @answer = Answer.find(params[:answer_id])
        redis_answer = Rails.cache.read(params[:answer_id]).split("@@")
        @question_id = redis_answer.first
        @answer_id = params[:answer_id]
        @correct = ActiveModel::Type::Boolean.new.cast(redis_answer.last)

        UserStatistic.set_statistic(@correct, current_user)
    end
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
    def questions
        @questions = Question.search(params[:term], page: params[:page], per_page: 5)
    end

    def subject
        @questions = Question._search_subject_(params[:page], params[:subject_id])
    end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @questions = Question.last_question(params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
    def msg_jumbotron
        case params[:action]
        when 'index'
            "Last questions registrated..."
        when 'questions'
            "Results to the search \"#{sanitize params[:term]}\"..."
        when 'subject'
            "Results to the theme \"#{sanitize params[:subject]}\"..."   
        end 
    end
end

app/views/site/shared/_questions.html.erb
<div class="jumbotron">
    <%= msg_jumbotron %>
</div>

<% @questions.each do |question| %>
    <%= form_with url: site_answer_path do |form| %>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <h3 class="panel-title">
                        <span class="label label-info" style="margin-right: 10px;">
                            <%= link_to "#{question.subject.description} (#{question.subject.questions_count})", site_search_subject_path(question.subject_id, question.subject.description), style:"color: white;" %>
                        </span>

                        <%= sanitize question.description %>
                    </h3>
                </h3>
            </div>

            <div class="panel-body">
                <ul>
                    <% question.answers.each do |answer| %>
                        <li style="list-style:none;" >
                            <div class="radio">
                                <label>
                                    <%= radio_button_tag 'answer_id', answer.id, false, disabled: false %>
                                    <%= content_tag :p, answer.description, id:"description_#{answer.id}" %>
                                </label>
                            </div>
                        </li>
                    <% end %>

                    <li style="list-style:none;" >
                        <%= form.submit "Check", class:"btn btn-default", id:"submit_#{question.id}" %>
                    </li>
                </ul>
            </div>
        </div>
    <% end %>
<% end %>

<% if user_signed_in? %>
    <div class="text-center">
        <%= paginate @questions %>
    </div>
<% else %>
    <div class="alert alert-warning" role="alert">
        Log in to continue
    </div>
<% end %>